// <auto-generated />
using System;
using DATripster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DALTripster.Migrations
{
    [DbContext(typeof(TripsterDB))]
    [Migration("20260213042104_seedingdata")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DALTripster.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            Description = "Luxury 5-star hotel",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Golden Nile Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "North Coast",
                            Description = "Beachfront resort",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "North Coast Resort"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Giza",
                            Description = "Historic hotel",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Royal Pyramids Hotel"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Sharm El Sheikh",
                            Description = "Diving resort",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Red Sea Resort"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Alexandria",
                            Description = "Boutique hotel",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Alexandria Palace"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HotelServices", (string)null);
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            ImageUrl = "/assets/hotelImg/hotel1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 2,
                            ImageUrl = "/assets/hotelImg/hotel2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 3,
                            ImageUrl = "/assets/hotelImg/hotel3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 4,
                            ImageUrl = "/assets/hotelImg/hotel4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 5,
                            ImageUrl = "/assets/hotelImg/hotel6.jpg"
                        },
                        new
                        {
                            Id = 6,
                            HotelId = 1,
                            ImageUrl = "/assets/roomImg/room-1.jpg",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 7,
                            HotelId = 1,
                            ImageUrl = "/assets/roomImg/room-2.jpg",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 8,
                            HotelId = 1,
                            ImageUrl = "/assets/roomImg/room-3.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 9,
                            HotelId = 2,
                            ImageUrl = "/assets/roomImg/room-4.jpg",
                            RoomId = 4
                        },
                        new
                        {
                            Id = 10,
                            HotelId = 2,
                            ImageUrl = "/assets/roomImg/room-5.jpg",
                            RoomId = 5
                        },
                        new
                        {
                            Id = 11,
                            HotelId = 2,
                            ImageUrl = "/assets/roomImg/room-6.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            Id = 12,
                            HotelId = 3,
                            ImageUrl = "/assets/roomImg/room-7.jpg",
                            RoomId = 7
                        },
                        new
                        {
                            Id = 13,
                            HotelId = 3,
                            ImageUrl = "/assets/roomImg/room-1.jpg",
                            RoomId = 8
                        },
                        new
                        {
                            Id = 14,
                            HotelId = 3,
                            ImageUrl = "/assets/roomImg/room-2.jpg",
                            RoomId = 9
                        },
                        new
                        {
                            Id = 15,
                            HotelId = 4,
                            ImageUrl = "/assets/roomImg/room-3.jpg",
                            RoomId = 10
                        },
                        new
                        {
                            Id = 16,
                            HotelId = 4,
                            ImageUrl = "/assets/roomImg/room-4.jpg",
                            RoomId = 11
                        },
                        new
                        {
                            Id = 17,
                            HotelId = 4,
                            ImageUrl = "/assets/roomImg/room-5.jpg",
                            RoomId = 12
                        },
                        new
                        {
                            Id = 18,
                            HotelId = 5,
                            ImageUrl = "/assets/roomImg/room-6.jpg",
                            RoomId = 13
                        },
                        new
                        {
                            Id = 19,
                            HotelId = 5,
                            ImageUrl = "/assets/roomImg/room-7.jpg",
                            RoomId = 14
                        },
                        new
                        {
                            Id = 20,
                            HotelId = 5,
                            ImageUrl = "/assets/roomImg/room-1.jpg",
                            RoomId = 15
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOFBathRoom")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Sqm")
                        .HasColumnType("real");

                    b.Property<int>("TypeOfBed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            HotelId = 1,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1200m,
                            RoomType = "Standard",
                            Sqm = 28f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            HotelId = 1,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1800m,
                            RoomType = "Deluxe",
                            Sqm = 38f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            HotelId = 1,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 2800m,
                            RoomType = "Suite",
                            Sqm = 55f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            HotelId = 2,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1300m,
                            RoomType = "Standard",
                            Sqm = 30f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            HotelId = 2,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 2000m,
                            RoomType = "Deluxe",
                            Sqm = 42f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            HotelId = 2,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 3200m,
                            RoomType = "Suite",
                            Sqm = 65f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 2,
                            HotelId = 3,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1100m,
                            RoomType = "Standard",
                            Sqm = 26f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            HotelId = 3,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1700m,
                            RoomType = "Deluxe",
                            Sqm = 40f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            HotelId = 3,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 2600m,
                            RoomType = "Suite",
                            Sqm = 52f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 2,
                            HotelId = 4,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1400m,
                            RoomType = "Standard",
                            Sqm = 32f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 2,
                            HotelId = 4,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 2100m,
                            RoomType = "Deluxe",
                            Sqm = 45f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            HotelId = 4,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 3500m,
                            RoomType = "Suite",
                            Sqm = 70f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 2,
                            HotelId = 5,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1000m,
                            RoomType = "Standard",
                            Sqm = 25f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 2,
                            HotelId = 5,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1600m,
                            RoomType = "Deluxe",
                            Sqm = 36f,
                            TypeOfBed = 0
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 4,
                            HotelId = 5,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 2400m,
                            RoomType = "Suite",
                            Sqm = 50f,
                            TypeOfBed = 0
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed@email.com",
                            ImageUrl = "/assets/userImgs/user1.jpg",
                            Location = "Cairo",
                            Name = "Ahmed Mohamed",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1988, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima@email.com",
                            ImageUrl = "/assets/userImgs/user2.jpg",
                            Location = "Alexandria",
                            Name = "Fatima Hassan",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahmoud@email.com",
                            ImageUrl = "/assets/userImgs/user3.jpg",
                            Location = "Giza",
                            Name = "Mahmoud Abdullah",
                            Nationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("HotelServices")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.Service", "Service")
                        .WithMany("HotelServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId");

                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId");

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Navigation("HotelServices");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Navigation("HotelServices");
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
