// <auto-generated />
using System;
using DATripster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DALTripster.Migrations
{
    [DbContext(typeof(TripsterDB))]
    [Migration("20260204215143_edit")]
    partial class edit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            TotalPrice = 285.0m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            TotalPrice = 900.0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            TotalPrice = 120.0m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Nile Street, Giza",
                            Description = "Family-friendly hotel near major attractions.",
                            Latitude = 29.9773,
                            Longitude = 31.1325,
                            Name = "Sunrise Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "88 Marina Road, Hurghada",
                            Description = "Beach resort with sea view rooms and water activities.",
                            Latitude = 27.257899999999999,
                            Longitude = 33.811599999999999,
                            Name = "Sea Breeze Resort"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HotelServices");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 4
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            ImageUrl = "https://picsum.photos/id/1018/900/600"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://picsum.photos/id/1019/900/600",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://picsum.photos/id/1020/900/600",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://picsum.photos/id/1021/900/600",
                            RoomId = 4
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Very clean and great service.",
                            HotelId = 1,
                            Rate = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Amazing beach view, would visit again!",
                            HotelId = 2,
                            Rate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Good for the price, but room was small.",
                            HotelId = 1,
                            Rate = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            HotelId = 1,
                            IsAvailable = true,
                            Price = 60.0m,
                            RoomType = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            HotelId = 1,
                            IsAvailable = true,
                            Price = 95.0m,
                            RoomType = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            HotelId = 2,
                            IsAvailable = true,
                            Price = 180.0m,
                            RoomType = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            HotelId = 2,
                            IsAvailable = false,
                            Price = 110.0m,
                            RoomType = "Double"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Free Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Breakfast Included"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Airport Pickup"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gym"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@gmail.com",
                            ImageUrl = "https://picsum.photos/id/1005/400/400",
                            Location = "New York",
                            Name = "John Doe",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1996, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.ali@gmail.com",
                            ImageUrl = "https://picsum.photos/id/1027/400/400",
                            Location = "Cairo",
                            Name = "Sara Ali",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1993, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.hassan@gmail.com",
                            ImageUrl = "https://picsum.photos/id/1011/400/400",
                            Location = "Alexandria",
                            Name = "Omar Hassan",
                            Nationality = "Egyptian"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("HotelServices")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.Service", "Service")
                        .WithMany("HotelServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId");

                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId");

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Navigation("HotelServices");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Navigation("HotelServices");
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
