// <auto-generated />
using System;
using DATripster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DALTripster.Migrations
{
    [DbContext(typeof(TripsterDB))]
    [Migration("20260211164627_fix data seed")]
    partial class fixdataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DALTripster.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            TotalPrice = 11000.00m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            TotalPrice = 11000.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            TotalPrice = 16000.00m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CheckIn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            TotalPrice = 15000.00m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CheckIn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 5,
                            TotalPrice = 9500.00m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nile Corniche, Cairo, Egypt",
                            Description = "Luxury 5-star hotel overlooking the Nile River with stunning views and world-class facilities",
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "Golden Nile Hotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "KM 120, North Coast, Egypt",
                            Description = "Elegant beachfront resort on the Mediterranean Sea offering an unforgettable relaxation experience",
                            Latitude = 30.891300000000001,
                            Longitude = 29.743400000000001,
                            Name = "North Coast Resort"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pyramid Street, Giza, Egypt",
                            Description = "Historic hotel near the Pyramids combining authenticity with modern comfort",
                            Latitude = 29.979199999999999,
                            Longitude = 31.1342,
                            Name = "Royal Pyramids Hotel"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tourist Promenade, Sharm El Sheikh, Egypt",
                            Description = "World-class diving resort on the Red Sea with spectacular coral reefs",
                            Latitude = 27.257899999999999,
                            Longitude = 33.811599999999999,
                            Name = "Red Sea Resort"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Alexandria Corniche, Alexandria, Egypt",
                            Description = "Luxury boutique hotel on the Mediterranean coast with rich historical heritage",
                            Latitude = 31.200099999999999,
                            Longitude = 29.918700000000001,
                            Name = "Alexandria Palace"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HotelServices", (string)null);

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 4
                        },
                        new
                        {
                            HotelId = 1,
                            ServiceId = 5
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            HotelId = 2,
                            ServiceId = 5
                        },
                        new
                        {
                            HotelId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            HotelId = 3,
                            ServiceId = 5
                        },
                        new
                        {
                            HotelId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            HotelId = 4,
                            ServiceId = 3
                        },
                        new
                        {
                            HotelId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            HotelId = 5,
                            ServiceId = 3
                        },
                        new
                        {
                            HotelId = 5,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            ImageUrl = "https://example.com/hotels/golden-nile/exterior.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 1,
                            ImageUrl = "https://example.com/hotels/golden-nile/royal-suite.jpg",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 2,
                            ImageUrl = "https://example.com/hotels/north-coast/beach-view.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 3,
                            ImageUrl = "https://example.com/hotels/pyramids/pyramid-view.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 4,
                            ImageUrl = "https://example.com/hotels/red-sea/diving-center.jpg"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent hotel! Outstanding service and the Nile view is fantastic. Highly recommended.",
                            HotelId = 1,
                            Rate = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good hotel with excellent location. Rooms are clean but breakfast needs improvement.",
                            HotelId = 1,
                            Rate = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Amazing beach resort! Clean beach and modern facilities. Unforgettable experience.",
                            HotelId = 2,
                            Rate = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Perfect location next to the Pyramids. Historic and luxurious hotel. Exceptional service.",
                            HotelId = 3,
                            Rate = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Great hotel for diving. Excellent facilities but rooms need renovation.",
                            HotelId = 4,
                            Rate = 4,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOFBathRoom")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Sqm")
                        .HasColumnType("real");

                    b.Property<int>("TypeOfBed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            HotelId = 1,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 3500.00m,
                            RoomType = "Royal Suite",
                            Sqm = 85.5f,
                            TypeOfBed = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            HotelId = 1,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 2200.00m,
                            RoomType = "Deluxe Nile View Room",
                            Sqm = 45f,
                            TypeOfBed = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            HotelId = 2,
                            IsAvailable = true,
                            NumberOFBathRoom = 2,
                            Price = 3200.00m,
                            RoomType = "Beach Front Chalet",
                            Sqm = 75f,
                            TypeOfBed = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            HotelId = 3,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 2500.00m,
                            RoomType = "Pyramid View Room",
                            Sqm = 50f,
                            TypeOfBed = 2
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 2,
                            HotelId = 4,
                            IsAvailable = true,
                            NumberOFBathRoom = 1,
                            Price = 1900.00m,
                            RoomType = "Divers Room",
                            Sqm = 40f,
                            TypeOfBed = 2
                        });
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Free WiFi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Outdoor Pool"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Spa & Wellness Center"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fitness Center"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fine Dining Restaurant"
                        });
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.mohamed@email.com",
                            ImageUrl = "https://example.com/images/users/ahmed.jpg",
                            Location = "Cairo, Egypt",
                            Name = "Ahmed Mohamed Ali",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1988, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.hassan@email.com",
                            ImageUrl = "https://example.com/images/users/fatima.jpg",
                            Location = "Alexandria, Egypt",
                            Name = "Fatima Hassan",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahmoud.abdullah@email.com",
                            ImageUrl = "https://example.com/images/users/mahmoud.jpg",
                            Location = "Giza, Egypt",
                            Name = "Mahmoud Abdullah",
                            Nationality = "Egyptian"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1985, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.aldeen@email.com",
                            ImageUrl = "https://example.com/images/users/nour.jpg",
                            Location = "Dubai, UAE",
                            Name = "Nour Al-Din",
                            Nationality = "Emirati"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1995, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.ahmed@email.com",
                            ImageUrl = "https://example.com/images/users/sara.jpg",
                            Location = "Riyadh, Saudi Arabia",
                            Name = "Sara Ahmed",
                            Nationality = "Saudi"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DATripster.Entities.Booking", b =>
                {
                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.HotelService", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("HotelServices")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.Service", "Service")
                        .WithMany("HotelServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DATripster.Entities.Image", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("HotelId");

                    b.HasOne("DATripster.Entities.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId");

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DATripster.Entities.Review", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DATripster.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.HasOne("DATripster.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DALTripster.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DATripster.Entities.Hotel", b =>
                {
                    b.Navigation("HotelServices");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DATripster.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DATripster.Entities.Service", b =>
                {
                    b.Navigation("HotelServices");
                });

            modelBuilder.Entity("DATripster.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
